version: "3.8"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      # If you want to provide a custom config, mount it here. Leave commented out to use embedded defaults.
      # - ./clickhouse_config:/etc/clickhouse-server
    ports:
      - "9000:9000"   # native TCP
      - "8123:8123"   # HTTP interface
      - "9009:9009"   # interserver (optional)
    env_file:
      - ./scripts/.env

  dbt-runner:
    build:
      context: ./dbt_runner
    container_name: dbt-runner
    restart: 'no'
    volumes:
      - ./:/workspace
      - ~/.dbt:/root/.dbt
    working_dir: /workspace
    # Run as the same UID/GID as ClickHouse so files created by dbt have correct ownership
    user: "101:101"
    entrypoint: ["/bin/bash","-lc"]
    command: ["/bin/bash","-lc","dbt debug --profiles-dir /root/.dbt && dbt run --profiles-dir /root/.dbt && dbt test --profiles-dir /root/.dbt"]

volumes:
  clickhouse_data:
